### ISSUE TITLE
IStep - Unable to change to current folder

### ISSUE THREAD

**Issue by ASK2135** [ogsteele/Analysis_Scripts#16]
**IStep returning error after first file selection (e.g., Cell X/000/Clamp1.ma)** 

Suggested to be pathing issue. Same result when running from command line or running IStep function. Same result with Github cloned repository or local copy. Same result when resetting path to default. Path set includes default MATLAB folders, matlab data folder (example data), matlab scripts folder (analysis scripts)

**Error produced:**
Error using cd
Unable to change current folder to
'C:\MATLAB_data\exampleData\CurrentStep\CC_IV_1_full_000\031' (Name is nonexistent or not a
folder).

Error in IStep>MAload (line 2314)
        cd(dirname);

Error in IStep>ephysIO (line 1054)
        [array,xdiff,xunit,yunit,names,notes,clist] = MAload (filename,ch);

Error in IStep (line 155)
S = ephysIO(clampfile);

**See screenshots of error below:**

![image](https://github.com/ogsteele/Analysis_Scripts/assets/145569561/7e69fca6-0297-4597-a65e-61da05ceab91)

xoxo

Dr Stuart-Kelly

**Comment by ogsteele** [comment]
So the issue originates from having the data folder in the path, generally this is a bad idea in MATLAB - and especially so in bodged code that i've written! **If you remove the MATLAB data folder from your path this issue should go away.** 

The issue actually lies with ephysIO (Andy's master code that underlies this code), which i'm reluctant to dive into. For now I will update the description of the code so this is clearer.

**Comment by ogsteele** [comment]
For future reference, this is a known and expected behaviour with ephysIO and is not planned to be changed. 

Users should avoid storing data on the path if that data is stored in sequential folders ('001', '002' etc) that has a higher folder number than the data you're telling it to analyse (ie, the data on the path has 31 folders and the data you're interested in analysing has 30 folders) as this will cause ephysIO, and therefore IStep, to throw an error and terminate the function prematurely.
